twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        BASE_URL: '%env(BASE_URL)%'
    paths:
        '%kernel.project_dir%/public': images

when@test:
    twig:
        strict_variables: true
